-- MySQL Script generated by MySQL Workbench
-- Sun Feb  5 18:24:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `Categoriascol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productos_categorias_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `productos_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` TEXT NOT NULL,
  `latitud` DECIMAL NOT NULL,
  `longitud` DECIMAL NOT NULL,
  `id_usuario` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `direccion_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `direccion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `id_usuario` bigint(20) unsigned NOT NULL,
  `id_direccion` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `carrit_usuarios_idx` (`id_usuario` ASC) ,
  INDEX `carrito_direccion_idx` (`id_direccion` ASC) ,
  CONSTRAINT `carrit_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carrito_direccion`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalles_carritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalles_carritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_carrito` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_detalle_carrito_idx` (`id_producto` ASC) ,
  INDEX `carrito_detalle_carrito_idx` (`id_carrito` ASC) ,
  CONSTRAINT `producto_detalle_carrito`
    FOREIGN KEY (`id_producto`)
    REFERENCES `Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carrito_detalle_carrito`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `carritos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sucursal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1024) NULL,
  `direccion` TEXT NULL,
  `latitud` DECIMAL NULL,
  `longitud` DECIMAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `existencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `existencia` (
  `id` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_sucursal` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `existencia_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `existencia_sucursal_idx` (`id_sucursal` ASC) VISIBLE,
  CONSTRAINT `existencia_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `existencia_sucursal`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


alter table carritos add column created_at timestamp null;
alter table carritos add column updated_at timestamp null;

alter table detalles_carritos add column created_at timestamp null;
alter table detalles_carritos add column updated_at timestamp null;

alter table detalles_carritos add column cantidad int not null;